### ISSUE TITLE
JavaScript heap out of memory

### ISSUE THREAD

**Issue by JamesMcMurran** [coinbase/coinbase-pro-trading-toolkit#110]
I let the example t002_liveOrderbook.ts run for a few hours and got the below error.

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
 1: node::Abort() [/usr/bin/node]
 2: 0x1356bec [/usr/bin/node]
 3: v8::Utils::ReportOOMFailure(char const*, bool) [/usr/bin/node]
 4: v8::internal::V8::FatalProcessOutOfMemory(char const*, bool) [/usr/bin/node]
 5: v8::internal::Factory::NewTransitionArray(int) [/usr/bin/node]
 6: v8::internal::TransitionArray::Insert(v8::internal::Handle<v8::internal::Map>, v8::internal::Handle<v8::internal::Name>, v8::internal::Handle<v8::internal::Map>, v8::internal::SimpleTransitionFlag) [/usr/bin/node]
 7: v8::internal::Map::CopyReplaceDescriptors(v8::internal::Handle<v8::internal::Map>, v8::internal::Handle<v8::internal::DescriptorArray>, v8::internal::Handle<v8::internal::LayoutDescriptor>, v8::internal::TransitionFlag, v8::internal::MaybeHandle<v8::internal::Name>, char const*, v8::internal::SimpleTransitionFlag) [/usr/bin/node]
 8: v8::internal::Map::CopyAddDescriptor(v8::internal::Handle<v8::internal::Map>, v8::internal::Descriptor*, v8::internal::TransitionFlag) [/usr/bin/node]
 9: v8::internal::Map::CopyWithField(v8::internal::Handle<v8::internal::Map>, v8::internal::Handle<v8::internal::Name>, v8::internal::Handle<v8::internal::FieldType>, v8::internal::PropertyAttributes, v8::internal::PropertyConstness, v8::internal::Representation, v8::internal::TransitionFlag) [/usr/bin/node]
10: v8::internal::Map::TransitionToDataProperty(v8::internal::Handle<v8::internal::Map>, v8::internal::Handle<v8::internal::Name>, v8::internal::Handle<v8::internal::Object>, v8::internal::PropertyAttributes, v8::internal::PropertyConstness, v8::internal::Object::StoreFromKeyed) [/usr/bin/node]
11: v8::internal::LookupIterator::PrepareTransitionToDataProperty(v8::internal::Handle<v8::internal::JSObject>, v8::internal::Handle<v8::internal::Object>, v8::internal::PropertyAttributes, v8::internal::Object::StoreFromKeyed) [/usr/bin/node]
12: v8::internal::StoreIC::LookupForWrite(v8::internal::LookupIterator*, v8::internal::Handle<v8::internal::Object>, v8::internal::Object::StoreFromKeyed) [/usr/bin/node]
13: v8::internal::StoreIC::UpdateCaches(v8::internal::LookupIterator*, v8::internal::Handle<v8::internal::Object>, v8::internal::Object::StoreFromKeyed) [/usr/bin/node]
14: v8::internal::StoreIC::Store(v8::internal::Handle<v8::internal::Object>, v8::internal::Handle<v8::internal::Name>, v8::internal::Handle<v8::internal::Object>, v8::internal::Object::StoreFromKeyed) [/usr/bin/node]
15: v8::internal::KeyedStoreIC::Store(v8::internal::Handle<v8::internal::Object>, v8::internal::Handle<v8::internal::Object>, v8::internal::Handle<v8::internal::Object>) [/usr/bin/node]
16: v8::internal::Runtime_KeyedStoreIC_Miss(int, v8::internal::Object**, v8::internal::Isolate*) [/usr/bin/node]
17: 0x3050d5846fd
Aborted (core dumped)

**Comment by jleonelion** [comment]
I have encountered this error many times too.  I have a simple application that connects to an exchange and logs the various events emitted by the LiveOrderbook.  It runs for ~4 hours that it falls over with the above.  By increasing max_old_space_size the program can run for a longer period of time, but it eventually falls over again.

After some profiling and code review, I have a strong suspicion the bid/ask trees in the BookBuilder continue to grow and until there is no more memory to consume.  

Is there a preference amongst the community on how to handle this?

It seems reasonable to introduce a "max depth" concept so the Bookbuilder only keeps bid/ask information within a certain range.  Another option is to have this information cached in a separate process (like Redis).

I can see this becoming a big problem if somebody creates an app that uses order books from multiple exchanges.

**Comment by saamalik** [comment]
I also spent the better part of the day debugging this, initially to learn about NodeJS, but in the  process learned a lot about Chrome Memory profiler, bintrees (Red-Black Trees, Binary Search Trees), NodeJS memory allocations, GC, etc....

And of course, in the end, the fix really is a (drum roll, please) _one-line_ change. So far I've been running `src/samples/liveOrderBook.ts` running for about 8 hours with stable memory (~170mb). We'll claim victory if it hits the 24 hour mark.

@CjS77 LiveOrderbook is implemented as a `Duplex` stream; on every `_write` we're pushing the message to the read queue (`this.push(msg)`). However, by default all Streams are in paused state, not in _flowing_ -- so all that level data is adding up fast but no one is reading from it.

We have the following options:

1. `LIveOrderbook` should be a `Writable`, not a `Duplex`. IMHO it makes sense for filters and transforms to be duplexes since they're always chained from source to sink. However, `LiveOrderbook` doesn't quite fit that bucket.
2. Force `LiveOrderbook` stream to be in _flowing_ state; essentially call `this.resume()` in constructor.
3. Add a `.on('data', () => {})` listener in both the t002 and sample/liveOrderbook sources to force stream in _flowing_ state.

IMHO I think Option 1 is the cleanest. Let me know if you agree and I'll open up a PR.

**Comment by mujud** [comment]
@saamalik option 3 resolved the issue for me thx.

**Comment by qbm5** [comment]
@saamalik  Thank you.  This was very helpful.  2 Worked for me

**Comment by CjS77** [comment]
@saamalik, yeah nice find! I've gone back and forth on  this a few times. I made LiveOrderbook Duplex with extensibility in mind, since I didn't want to presuppose that it's always at the end of a stream chain. However, as you correctly point out, if it _is_ at the end of the chain, the write buffer will eventually overflow.

Since the data is simply being pushed down the stream unchanged, I agree that option 1 is the "write" way to go (bad pun alert!). If users want additional consumers of the inbound message stream, we should look at a `StreamDuplicator` filter.

**Comment by jrhite** [comment]
i have been running into the same problem.

good find!

any PR on this? didn't see anything.

**Comment by blair** [comment]
@CjS77 Why is StreamDuplicator needed? My understanding is that a Readable can have any number of pipes attached to it.

**Comment by drewrothstein** [comment]
Hi, we are closing out PRs + Issues as this project is being archived.
