### ISSUE TITLE
Consider a `SettledOrder` type

### ISSUE THREAD

**Issue by CjS77** [coinbase/coinbase-pro-trading-toolkit#56]
We should consider adding `SettledOrder` as a distinct type to `LiveOrder`

This would add fields that are not typically known for 'live' orders, such as settled time and fees charged.

The price semantics are also potentially different (e.g. settled market orders are often matched against multiple resting orders and so only have an average price)

**Comment by elby22** [comment]
I'm thinking about ways this might get implemented. the `AuthenticatedExchangeAPI` offers `loadAllOrders(gdaxProduct: string)`. Without breaking that method we could create a method like `loadAllClosedOrders(gdaxProduct: string)`. For the `GDAXExchangeAPI` implementation of both these methods, we could create a private method that handles the calling of `loadNextOrders()`, but passes in the array of statuses instead of declaring them in the function.

**Comment by drewrothstein** [comment]
Hi, we are closing out PRs + Issues as this project is being archived.
